name: CI/CD for FastAPI Chatbot

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set .env
        run: | 
          echo ${{ secrets.DOT_ENV }} >> ./.env

      - name: Debug DOCKERHUB_REPO
        run: |
          echo "DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build & push to DockerHub
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/chatbot:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/chatbot:cache,mode=max \
            -t ${{ secrets.DOCKERHUB_REPO }}/chatbot:latest \
            --push .

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping existing chatbot container..."
            docker-compose stop chatbot || true
            
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_REPO }}/chatbot:latest
            
            echo "Restarting chatbot services..."
            docker-compose up -d chatbot
            
            echo "Waiting for FastAPI to start..."
            sleep 10
